# Site Configuration

theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Berlin

title: Mubashir Usman's Blog
tagline: SRE learnings and distributed systems notes
description: >-
  My learnings as a site reliability engineer and building reliable systems for production.
  I sometimes post my thoughts on navigating life in general.

url: "https://mubashirusman.github.io"
baseurl: ""

future: true

github:
  username: mubashirusman

social:
  name: Mubashir Usman
  email: mubashirusman016@gmail.com
  links:
    - https://www.linkedin.com/in/mubashir-usman-ijaz/
    - https://github.com/mubashirusman

toc: true
paginate: 10

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

kramdown:
  footnote_backlink: "&#8617;︎"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

exclude:
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
